# Usign the Clean Blog theme

title: Homepage of Yeechong Yeung
author: Yeechong Yeung
email: yeechongyeung@gmail.com
description: Homepage of Yeechong Yeung
baseurl: ""
url: "http://erchowyo.github.io/"
github_username:  erchowyo
twitter_username: yeechongyeung

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: Yeechong Yeung, recent works
gems:
  - jekyll-feed
